'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.wsSoap")>  _
    Public Interface wsSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SendEmailWithAttachments", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function SendEmailWithAttachments(ByVal sendEmailWithAttachmentsRequest As ServiceReference1.SendEmailWithAttachmentsRequest) As ServiceReference1.SendEmailWithAttachmentsResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SendEmailWithAttachments", ReplyAction:="*")>  _
        Function SendEmailWithAttachmentsAsync(ByVal sendEmailWithAttachmentsRequest As ServiceReference1.SendEmailWithAttachmentsRequest) As System.Threading.Tasks.Task(Of ServiceReference1.SendEmailWithAttachmentsResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetToken", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetToken(ByVal username As String, ByVal password As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetToken", ReplyAction:="*")>  _
        Function GetTokenAsync(ByVal username As String, ByVal password As String) As System.Threading.Tasks.Task(Of String)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SendEmailWithAttachmentsRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private tokenField As String
        
        Private emailField As SerEmail
        
        Private smtpClientField As SerSmtpClient
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Token() As String
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
                Me.RaisePropertyChanged("Token")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Email() As SerEmail
            Get
                Return Me.emailField
            End Get
            Set
                Me.emailField = value
                Me.RaisePropertyChanged("Email")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property SmtpClient() As SerSmtpClient
            Get
                Return Me.smtpClientField
            End Get
            Set
                Me.smtpClientField = value
                Me.RaisePropertyChanged("SmtpClient")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SerEmail
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private addressesEmailField() As SerMailAddress
        
        Private bccsEmailField() As SerMailAddress
        
        Private attachmentsField() As SerAttachment
        
        Private subjectField As String
        
        Private bodyField As String
        
        Private senderEmailField As SerMailAddress
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=0)>  _
        Public Property AddressesEmail() As SerMailAddress()
            Get
                Return Me.addressesEmailField
            End Get
            Set
                Me.addressesEmailField = value
                Me.RaisePropertyChanged("AddressesEmail")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=1)>  _
        Public Property BccsEmail() As SerMailAddress()
            Get
                Return Me.bccsEmailField
            End Get
            Set
                Me.bccsEmailField = value
                Me.RaisePropertyChanged("BccsEmail")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=2)>  _
        Public Property Attachments() As SerAttachment()
            Get
                Return Me.attachmentsField
            End Get
            Set
                Me.attachmentsField = value
                Me.RaisePropertyChanged("Attachments")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property Subject() As String
            Get
                Return Me.subjectField
            End Get
            Set
                Me.subjectField = value
                Me.RaisePropertyChanged("Subject")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property Body() As String
            Get
                Return Me.bodyField
            End Get
            Set
                Me.bodyField = value
                Me.RaisePropertyChanged("Body")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property SenderEmail() As SerMailAddress
            Get
                Return Me.senderEmailField
            End Get
            Set
                Me.senderEmailField = value
                Me.RaisePropertyChanged("SenderEmail")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SerMailAddress
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private addressField As String
        
        Private displayNameField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Address() As String
            Get
                Return Me.addressField
            End Get
            Set
                Me.addressField = value
                Me.RaisePropertyChanged("Address")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property DisplayName() As String
            Get
                Return Me.displayNameField
            End Get
            Set
                Me.displayNameField = value
                Me.RaisePropertyChanged("DisplayName")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SendEmailWithAttachmentsResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private hasErrorField As Boolean
        
        Private messageErrorField As String
        
        Private errorStackTraceField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property HasError() As Boolean
            Get
                Return Me.hasErrorField
            End Get
            Set
                Me.hasErrorField = value
                Me.RaisePropertyChanged("HasError")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property MessageError() As String
            Get
                Return Me.messageErrorField
            End Get
            Set
                Me.messageErrorField = value
                Me.RaisePropertyChanged("MessageError")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property ErrorStackTrace() As String
            Get
                Return Me.errorStackTraceField
            End Get
            Set
                Me.errorStackTraceField = value
                Me.RaisePropertyChanged("ErrorStackTrace")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SerSmtpClient
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private hostField As String
        
        Private portField As String
        
        Private credentialsUsernameField As String
        
        Private credentialsPasswordField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Host() As String
            Get
                Return Me.hostField
            End Get
            Set
                Me.hostField = value
                Me.RaisePropertyChanged("Host")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Port() As String
            Get
                Return Me.portField
            End Get
            Set
                Me.portField = value
                Me.RaisePropertyChanged("Port")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property CredentialsUsername() As String
            Get
                Return Me.credentialsUsernameField
            End Get
            Set
                Me.credentialsUsernameField = value
                Me.RaisePropertyChanged("CredentialsUsername")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property CredentialsPassword() As String
            Get
                Return Me.credentialsPasswordField
            End Get
            Set
                Me.credentialsPasswordField = value
                Me.RaisePropertyChanged("CredentialsPassword")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SerAttachment
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private fileNameField As String
        
        Private contentField() As Byte
        
        Private contentTypeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property FileName() As String
            Get
                Return Me.fileNameField
            End Get
            Set
                Me.fileNameField = value
                Me.RaisePropertyChanged("FileName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", Order:=1)>  _
        Public Property Content() As Byte()
            Get
                Return Me.contentField
            End Get
            Set
                Me.contentField = value
                Me.RaisePropertyChanged("Content")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property ContentType() As String
            Get
                Return Me.contentTypeField
            End Get
            Set
                Me.contentTypeField = value
                Me.RaisePropertyChanged("ContentType")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface wsSoapChannel
        Inherits ServiceReference1.wsSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class wsSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.wsSoap)
        Implements ServiceReference1.wsSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function SendEmailWithAttachments(ByVal sendEmailWithAttachmentsRequest As ServiceReference1.SendEmailWithAttachmentsRequest) As ServiceReference1.SendEmailWithAttachmentsResponse Implements ServiceReference1.wsSoap.SendEmailWithAttachments
            Return MyBase.Channel.SendEmailWithAttachments(sendEmailWithAttachmentsRequest)
        End Function
        
        Public Function SendEmailWithAttachmentsAsync(ByVal sendEmailWithAttachmentsRequest As ServiceReference1.SendEmailWithAttachmentsRequest) As System.Threading.Tasks.Task(Of ServiceReference1.SendEmailWithAttachmentsResponse) Implements ServiceReference1.wsSoap.SendEmailWithAttachmentsAsync
            Return MyBase.Channel.SendEmailWithAttachmentsAsync(sendEmailWithAttachmentsRequest)
        End Function
        
        Public Function GetToken(ByVal username As String, ByVal password As String) As String Implements ServiceReference1.wsSoap.GetToken
            Return MyBase.Channel.GetToken(username, password)
        End Function
        
        Public Function GetTokenAsync(ByVal username As String, ByVal password As String) As System.Threading.Tasks.Task(Of String) Implements ServiceReference1.wsSoap.GetTokenAsync
            Return MyBase.Channel.GetTokenAsync(username, password)
        End Function
    End Class
End Namespace
